/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import dao.PacienteDAO;
import java.awt.Color;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Paciente;


/**
 *
 * @author leia6
 */
public class DialogoBuscarPaciente extends javax.swing.JDialog {

    private Paciente pacienteSeleccionado;

    public Paciente getPacienteSeleccionado() {
        return pacienteSeleccionado;
    }

    public DialogoBuscarPaciente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        personalizarTabla();
    }

    private void personalizarTabla() {
        tblResultados.setBackground(Color.WHITE);
        tblResultados.setForeground(Color.BLACK);
        tblResultados.setSelectionBackground(new Color(79, 129, 189));
        tblResultados.setSelectionForeground(Color.WHITE);
        tblResultados.setRowHeight(22);

        tblResultados.getTableHeader().setBackground(new Color(220, 230, 241));
        tblResultados.getTableHeader().setForeground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        panelDatosPaciente = new javax.swing.JPanel();
        datosPaciente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        formularioPaciente = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtCip = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        panelBtnBuscar = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        panelInferior = new javax.swing.JPanel();
        panelBtnAceptar = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JLabel();
        panelBtnCancelar = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel1.setLayout(new java.awt.BorderLayout());

        panelSuperior.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Buscar Paciente");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        panelSuperior.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelCentral.setBackground(new java.awt.Color(255, 255, 255));
        panelCentral.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        panelCentral.setLayout(new javax.swing.BoxLayout(panelCentral, javax.swing.BoxLayout.Y_AXIS));

        panelDatosPaciente.setBackground(new java.awt.Color(243, 245, 249));
        panelDatosPaciente.setLayout(new java.awt.BorderLayout());

        datosPaciente.setBackground(new java.awt.Color(215, 232, 247));
        datosPaciente.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        datosPaciente.setMinimumSize(new java.awt.Dimension(124, 70));
        datosPaciente.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Datos del paciente");
        datosPaciente.add(jLabel2, java.awt.BorderLayout.WEST);

        panelDatosPaciente.add(datosPaciente, java.awt.BorderLayout.NORTH);

        formularioPaciente.setMaximumSize(new java.awt.Dimension(2147483647, 180));
        formularioPaciente.setMinimumSize(new java.awt.Dimension(1006, 160));
        formularioPaciente.setOpaque(false);
        formularioPaciente.setPreferredSize(new java.awt.Dimension(956, 160));
        formularioPaciente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("CIP");
        formularioPaciente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 31, -1, -1));

        txtApellidos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        formularioPaciente.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 336, 29));

        txtCip.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        formularioPaciente.add(txtCip, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 59, 336, 29));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Apellidos");
        formularioPaciente.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, -1, -1));

        panelBtnBuscar.setBackground(new java.awt.Color(75, 113, 167));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupab.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBtnBuscarLayout = new javax.swing.GroupLayout(panelBtnBuscar);
        panelBtnBuscar.setLayout(panelBtnBuscarLayout);
        panelBtnBuscarLayout.setHorizontalGroup(
            panelBtnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        panelBtnBuscarLayout.setVerticalGroup(
            panelBtnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        formularioPaciente.add(panelBtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 130, 140, -1));

        tblResultados.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CIP", "Apellidos", "Nombre", "Fecha de nacimiento"
            }
        ));
        tblResultados.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblResultados);

        formularioPaciente.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 680, 220));

        panelDatosPaciente.add(formularioPaciente, java.awt.BorderLayout.LINE_START);

        panelCentral.add(panelDatosPaciente);

        jPanel1.add(panelCentral, java.awt.BorderLayout.CENTER);

        panelInferior.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 20));
        panelInferior.setMinimumSize(new java.awt.Dimension(150, 53));
        panelInferior.setPreferredSize(new java.awt.Dimension(150, 53));

        panelBtnAceptar.setBackground(new java.awt.Color(75, 113, 167));

        btnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAceptar.setText("Aceptar");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBtnAceptarLayout = new javax.swing.GroupLayout(panelBtnAceptar);
        panelBtnAceptar.setLayout(panelBtnAceptarLayout);
        panelBtnAceptarLayout.setHorizontalGroup(
            panelBtnAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnAceptarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBtnAceptarLayout.setVerticalGroup(
            panelBtnAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnAceptarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelInferior.add(panelBtnAceptar);

        panelBtnCancelar.setBackground(new java.awt.Color(75, 113, 167));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBtnCancelarLayout = new javax.swing.GroupLayout(panelBtnCancelar);
        panelBtnCancelar.setLayout(panelBtnCancelarLayout);
        panelBtnCancelarLayout.setHorizontalGroup(
            panelBtnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnCancelarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBtnCancelarLayout.setVerticalGroup(
            panelBtnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnCancelarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelInferior.add(panelBtnCancelar);

        jPanel1.add(panelInferior, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 791, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        int fila = tblResultados.getSelectedRow();

        if (fila != -1) {
            String cip = tblResultados.getValueAt(fila, 0).toString();
            String apellidos = tblResultados.getValueAt(fila, 1).toString();
            String nombre = tblResultados.getValueAt(fila, 2).toString();
            LocalDate fecha = LocalDate.parse(tblResultados.getValueAt(fila, 3).toString());

            pacienteSeleccionado = new Paciente(cip, nombre, apellidos, fecha);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un paciente");
        }
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        String cip = txtCip.getText().trim();
        String apellidos = txtApellidos.getText().trim();

        if (!cip.isEmpty()) {
            buscarPorCip(cip);
        } else if (!apellidos.isEmpty()) {
            buscarPorApellidos(apellidos);
        } else {
            JOptionPane.showMessageDialog(this, "Introduce CIP o apellidos");
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void buscarPorCip(String cip) {
        PacienteDAO dao = new PacienteDAO();
        Paciente p = dao.buscarPorCip(cip);

        DefaultTableModel modelo = (DefaultTableModel) tblResultados.getModel();
        modelo.setRowCount(0);

        if (p != null) {
            modelo.addRow(new Object[]{
                p.getCip(),
                p.getApellidos(),
                p.getNombre(),
                p.getFechaNacimiento()
            });
        } else {
            JOptionPane.showMessageDialog(this, "Paciente no encontrado");
        }
    }

    private void buscarPorApellidos(String apellidos) {
        PacienteDAO dao = new PacienteDAO();
        List<Paciente> lista = dao.buscarPorApellidos(apellidos);

        DefaultTableModel modelo = (DefaultTableModel) tblResultados.getModel();
        modelo.setRowCount(0);

        for (Paciente p : lista) {
            modelo.addRow(new Object[]{
                p.getCip(),
                p.getApellidos(),
                p.getNombre(),
                p.getFechaNacimiento()
            });
        }

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontraron pacientes");
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAceptar;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JPanel datosPaciente;
    private javax.swing.JPanel formularioPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelBtnAceptar;
    private javax.swing.JPanel panelBtnBuscar;
    private javax.swing.JPanel panelBtnCancelar;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelDatosPaciente;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCip;
    // End of variables declaration//GEN-END:variables
}
