/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import dao.PacienteDAO;
import dao.PeticionDAO;
import dao.TipoMuestraDAO;
import java.awt.CardLayout;
import java.awt.Color;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.EnumEstadoPeticion;
import model.Paciente;
import model.Peticion;
import model.TipoMuestra;


/**
 *
 * @author leia6
 */
public class PanelPendientesResultados extends javax.swing.JPanel {

    private JPanel panelPrincipal;
    private PanelGestionPeticion pnlGestionPeticion;
    private Map<Integer, String> mapaTiposMuestra = new HashMap<>();
   

    public PanelPendientesResultados(JPanel panelPrincipal, PanelGestionPeticion pnlGestionPeticion) {
        this.panelPrincipal = panelPrincipal;
        this.pnlGestionPeticion = pnlGestionPeticion;
        initComponents();
        personalizarTabla();
        cargarMapaTiposMuestra();
    }

    private void personalizarTabla() {
        tblPendientes.setBackground(Color.WHITE);
        tblPendientes.setForeground(Color.BLACK);
        tblPendientes.setSelectionBackground(new Color(79, 129, 189));
        tblPendientes.setSelectionForeground(Color.WHITE);
        tblPendientes.setRowHeight(22);

        tblPendientes.getTableHeader().setBackground(new Color(220, 230, 241));
        tblPendientes.getTableHeader().setForeground(Color.BLACK);
    }

    public void cargarPendientes() {
        PeticionDAO dao = new PeticionDAO();
        PacienteDAO pacienteDAO = new PacienteDAO();

        List<Peticion> lista = dao.listarPorEstado(EnumEstadoPeticion.PENDIENTE);

        DefaultTableModel modelo = (DefaultTableModel) tblPendientes.getModel();
        modelo.setRowCount(0);

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

        for (Peticion p : lista) {
            Paciente paciente = pacienteDAO.buscarPorCip(p.getCipPaciente());

            modelo.addRow(new Object[]{
                p.getIdPeticion(),
                p.getFechaRegistro().format(formatter),
                paciente != null ? paciente.getApellidos() + ", " + paciente.getNombre() : "--",
                p.getCipPaciente(),
                p.getPrioridad(),
                mapaTiposMuestra.getOrDefault(p.getIdTipoMuestra(), "--")
            });
        }
    }

    private void cargarMapaTiposMuestra() {
        TipoMuestraDAO dao = new TipoMuestraDAO();
        List<TipoMuestra> lista = dao.listarTodos();

        mapaTiposMuestra.clear();

        for (TipoMuestra tm : lista) {
            mapaTiposMuestra.put(tm.getId(), tm.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPrioridad = new javax.swing.ButtonGroup();
        panelSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        panelDatosPeticion = new javax.swing.JPanel();
        detallesPeticion = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPendientes = new javax.swing.JTable();
        panelInferior = new javax.swing.JPanel();
        panelBtnCancelar = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JLabel();
        panelBtnAbrir = new javax.swing.JPanel();
        btnAbrir = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout());

        panelSuperior.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Peticiones pendientes de resultados");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        panelSuperior.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelCentral.setBackground(new java.awt.Color(255, 255, 255));
        panelCentral.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        panelCentral.setLayout(new javax.swing.BoxLayout(panelCentral, javax.swing.BoxLayout.Y_AXIS));

        panelDatosPeticion.setBackground(new java.awt.Color(243, 245, 249));
        panelDatosPeticion.setLayout(new java.awt.BorderLayout());

        detallesPeticion.setBackground(new java.awt.Color(215, 232, 247));
        detallesPeticion.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        detallesPeticion.setMinimumSize(new java.awt.Dimension(124, 30));
        detallesPeticion.setPreferredSize(new java.awt.Dimension(381, 30));
        detallesPeticion.setLayout(new java.awt.BorderLayout());
        panelDatosPeticion.add(detallesPeticion, java.awt.BorderLayout.NORTH);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        tblPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº Petición", "Fecha", "Paciente", "CIP", "Prioridad", "Tipo de muestra"
            }
        ));
        tblPendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPendientesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPendientes);

        panelDatosPeticion.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        panelCentral.add(panelDatosPeticion);

        add(panelCentral, java.awt.BorderLayout.CENTER);

        panelInferior.setBackground(new java.awt.Color(255, 255, 255));
        panelInferior.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 20));
        panelInferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        panelBtnCancelar.setBackground(new java.awt.Color(243, 245, 249));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBtnCancelarLayout = new javax.swing.GroupLayout(panelBtnCancelar);
        panelBtnCancelar.setLayout(panelBtnCancelarLayout);
        panelBtnCancelarLayout.setHorizontalGroup(
            panelBtnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnCancelarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBtnCancelarLayout.setVerticalGroup(
            panelBtnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnCancelarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelInferior.add(panelBtnCancelar);

        panelBtnAbrir.setBackground(new java.awt.Color(75, 113, 167));

        btnAbrir.setBackground(new java.awt.Color(255, 255, 255));
        btnAbrir.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAbrir.setForeground(new java.awt.Color(255, 255, 255));
        btnAbrir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAbrir.setText("Abrir");
        btnAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbrirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBtnAbrirLayout = new javax.swing.GroupLayout(panelBtnAbrir);
        panelBtnAbrir.setLayout(panelBtnAbrirLayout);
        panelBtnAbrirLayout.setHorizontalGroup(
            panelBtnAbrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnAbrirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBtnAbrirLayout.setVerticalGroup(
            panelBtnAbrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnAbrirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelInferior.add(panelBtnAbrir);

        add(panelInferior, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseClicked
        
        int fila = tblPendientes.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una petición.");
            return;
        }

        int idPeticion = Integer.parseInt(tblPendientes.getValueAt(fila, 0).toString());
        
        pnlGestionPeticion.cargarPeticion(idPeticion);

        CardLayout cl = (CardLayout) panelPrincipal.getLayout();
        cl.show(panelPrincipal, "Gestion peticion");


    }//GEN-LAST:event_btnAbrirMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked



        CardLayout cl = (CardLayout) panelPrincipal.getLayout();
        cl.show(panelPrincipal, "Pantalla Inicio");
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void tblPendientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPendientesMouseClicked
        if (evt.getClickCount() == 2) {
            int fila = tblPendientes.getSelectedRow();

            if (fila != -1) {
                int idPeticion = Integer.parseInt(tblPendientes.getValueAt(fila, 0).toString());

                pnlGestionPeticion.cargarPeticion(idPeticion);

                CardLayout cl = (CardLayout) panelPrincipal.getLayout();
                cl.show(panelPrincipal, "Gestion peticion");
            }
        }
    }//GEN-LAST:event_tblPendientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAbrir;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.ButtonGroup buttonGroupPrioridad;
    private javax.swing.JPanel detallesPeticion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelBtnAbrir;
    private javax.swing.JPanel panelBtnCancelar;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelDatosPeticion;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTable tblPendientes;
    // End of variables declaration//GEN-END:variables
}
