/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JPanel;

/**
 *
 * @author leia6
 */
public class PanelInicio extends javax.swing.JPanel {

    private JPanel panelPrincipal;
    
    public PanelInicio(JPanel panelPrincipal) {
        this.panelPrincipal = panelPrincipal;
        initComponents();
    }

    private void colorEntrar(JPanel panel){
        panel.setBackground(new Color(230, 232, 235));
        panel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    
    private void colorSalir(JPanel panel){
        panel.setBackground(new Color(243, 245, 249));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblAcciones = new javax.swing.JLabel();
        pnlTarjetas = new javax.swing.JPanel();
        pnlNuevaPeticion = new javax.swing.JPanel();
        lblNuevaPeticion = new javax.swing.JLabel();
        pnlPendienteResultados = new javax.swing.JPanel();
        lblPendResultados = new javax.swing.JLabel();
        pnlPendienteValidacion = new javax.swing.JPanel();
        lblPendValidacion = new javax.swing.JLabel();
        pnlGenerarInforme = new javax.swing.JPanel();
        lblGenerarInforme = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAcciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAcciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAcciones.setText("Acciones rápidas");
        lblAcciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 20, 1));
        add(lblAcciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        pnlTarjetas.setBackground(new java.awt.Color(255, 255, 255));
        pnlTarjetas.setMaximumSize(new java.awt.Dimension(1000, 600));
        pnlTarjetas.setLayout(new java.awt.GridBagLayout());

        pnlNuevaPeticion.setBackground(new java.awt.Color(243, 245, 249));
        pnlNuevaPeticion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlNuevaPeticion.setMaximumSize(new java.awt.Dimension(350, 100));
        pnlNuevaPeticion.setMinimumSize(new java.awt.Dimension(350, 100));
        pnlNuevaPeticion.setName(""); // NOI18N
        pnlNuevaPeticion.setPreferredSize(new java.awt.Dimension(350, 100));
        pnlNuevaPeticion.setLayout(new java.awt.BorderLayout());

        lblNuevaPeticion.setBackground(new java.awt.Color(243, 245, 249));
        lblNuevaPeticion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNuevaPeticion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nueva_peticion.png"))); // NOI18N
        lblNuevaPeticion.setText("Nueva Petición");
        lblNuevaPeticion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        lblNuevaPeticion.setMaximumSize(new java.awt.Dimension(400, 120));
        lblNuevaPeticion.setMinimumSize(new java.awt.Dimension(400, 120));
        lblNuevaPeticion.setName(""); // NOI18N
        lblNuevaPeticion.setPreferredSize(new java.awt.Dimension(400, 120));
        lblNuevaPeticion.setRequestFocusEnabled(false);
        lblNuevaPeticion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNuevaPeticionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNuevaPeticionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNuevaPeticionMouseExited(evt);
            }
        });
        pnlNuevaPeticion.add(lblNuevaPeticion, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlTarjetas.add(pnlNuevaPeticion, gridBagConstraints);

        pnlPendienteResultados.setBackground(new java.awt.Color(243, 245, 249));
        pnlPendienteResultados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlPendienteResultados.setMaximumSize(new java.awt.Dimension(350, 100));
        pnlPendienteResultados.setMinimumSize(new java.awt.Dimension(350, 100));
        pnlPendienteResultados.setName(""); // NOI18N
        pnlPendienteResultados.setPreferredSize(new java.awt.Dimension(350, 100));
        pnlPendienteResultados.setLayout(new java.awt.BorderLayout());

        lblPendResultados.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPendResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pendiente_resultados.png"))); // NOI18N
        lblPendResultados.setText("<html>Pendientes de<br>resultados</html>");
        lblPendResultados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        lblPendResultados.setMaximumSize(new java.awt.Dimension(400, 120));
        lblPendResultados.setMinimumSize(new java.awt.Dimension(400, 120));
        lblPendResultados.setPreferredSize(new java.awt.Dimension(400, 120));
        lblPendResultados.setRequestFocusEnabled(false);
        lblPendResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPendResultadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPendResultadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPendResultadosMouseExited(evt);
            }
        });
        pnlPendienteResultados.add(lblPendResultados, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlTarjetas.add(pnlPendienteResultados, gridBagConstraints);

        pnlPendienteValidacion.setBackground(new java.awt.Color(243, 245, 249));
        pnlPendienteValidacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlPendienteValidacion.setMaximumSize(new java.awt.Dimension(350, 100));
        pnlPendienteValidacion.setMinimumSize(new java.awt.Dimension(350, 100));
        pnlPendienteValidacion.setName(""); // NOI18N
        pnlPendienteValidacion.setPreferredSize(new java.awt.Dimension(350, 100));
        pnlPendienteValidacion.setLayout(new java.awt.BorderLayout());

        lblPendValidacion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPendValidacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pendiente_validacion.png"))); // NOI18N
        lblPendValidacion.setText("<html>Pendientes de<br>validación</html>");
        lblPendValidacion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        lblPendValidacion.setMaximumSize(new java.awt.Dimension(400, 120));
        lblPendValidacion.setMinimumSize(new java.awt.Dimension(400, 120));
        lblPendValidacion.setPreferredSize(new java.awt.Dimension(400, 120));
        lblPendValidacion.setRequestFocusEnabled(false);
        lblPendValidacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPendValidacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPendValidacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPendValidacionMouseExited(evt);
            }
        });
        pnlPendienteValidacion.add(lblPendValidacion, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlTarjetas.add(pnlPendienteValidacion, gridBagConstraints);

        pnlGenerarInforme.setBackground(new java.awt.Color(243, 245, 249));
        pnlGenerarInforme.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlGenerarInforme.setMaximumSize(new java.awt.Dimension(350, 100));
        pnlGenerarInforme.setMinimumSize(new java.awt.Dimension(350, 100));
        pnlGenerarInforme.setName(""); // NOI18N
        pnlGenerarInforme.setPreferredSize(new java.awt.Dimension(350, 100));
        pnlGenerarInforme.setLayout(new java.awt.BorderLayout());

        lblGenerarInforme.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblGenerarInforme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/generar_informe.png"))); // NOI18N
        lblGenerarInforme.setText("Generar informe");
        lblGenerarInforme.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        lblGenerarInforme.setMaximumSize(new java.awt.Dimension(400, 120));
        lblGenerarInforme.setMinimumSize(new java.awt.Dimension(400, 120));
        lblGenerarInforme.setPreferredSize(new java.awt.Dimension(400, 120));
        lblGenerarInforme.setRequestFocusEnabled(false);
        lblGenerarInforme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGenerarInformeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGenerarInformeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGenerarInformeMouseExited(evt);
            }
        });
        pnlGenerarInforme.add(lblGenerarInforme, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlTarjetas.add(pnlGenerarInforme, gridBagConstraints);

        add(pnlTarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 118, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lblNuevaPeticionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevaPeticionMouseClicked
        ((CardLayout) panelPrincipal.getLayout())
        .show(panelPrincipal, "Nueva Peticion");
    }//GEN-LAST:event_lblNuevaPeticionMouseClicked

    private void lblNuevaPeticionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevaPeticionMouseEntered
        colorEntrar(pnlNuevaPeticion);
    }//GEN-LAST:event_lblNuevaPeticionMouseEntered

    private void lblNuevaPeticionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevaPeticionMouseExited
        colorSalir(pnlNuevaPeticion);
    }//GEN-LAST:event_lblNuevaPeticionMouseExited

    private void lblPendResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendResultadosMouseClicked
        
    }//GEN-LAST:event_lblPendResultadosMouseClicked

    private void lblPendResultadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendResultadosMouseEntered
        colorEntrar(pnlPendienteResultados);
    }//GEN-LAST:event_lblPendResultadosMouseEntered

    private void lblPendResultadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendResultadosMouseExited
        colorSalir(pnlPendienteResultados);
    }//GEN-LAST:event_lblPendResultadosMouseExited

    private void lblPendValidacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendValidacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPendValidacionMouseClicked

    private void lblPendValidacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendValidacionMouseEntered
        colorEntrar(pnlPendienteValidacion);
    }//GEN-LAST:event_lblPendValidacionMouseEntered

    private void lblPendValidacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendValidacionMouseExited
        colorSalir(pnlPendienteValidacion);
    }//GEN-LAST:event_lblPendValidacionMouseExited

    private void lblGenerarInformeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenerarInformeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGenerarInformeMouseClicked

    private void lblGenerarInformeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenerarInformeMouseEntered
        colorEntrar(pnlGenerarInforme);
    }//GEN-LAST:event_lblGenerarInformeMouseEntered

    private void lblGenerarInformeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenerarInformeMouseExited
        colorSalir(pnlGenerarInforme);
    }//GEN-LAST:event_lblGenerarInformeMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAcciones;
    private javax.swing.JLabel lblGenerarInforme;
    private javax.swing.JLabel lblNuevaPeticion;
    private javax.swing.JLabel lblPendResultados;
    private javax.swing.JLabel lblPendValidacion;
    private javax.swing.JPanel pnlGenerarInforme;
    private javax.swing.JPanel pnlNuevaPeticion;
    private javax.swing.JPanel pnlPendienteResultados;
    private javax.swing.JPanel pnlPendienteValidacion;
    private javax.swing.JPanel pnlTarjetas;
    // End of variables declaration//GEN-END:variables
}
