/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author leia6
 */
public class PanelInicio extends javax.swing.JPanel {

    /**
     * Creates new form pnlPantallaPrincipal
     */
    public PanelInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblAcciones = new javax.swing.JLabel();
        pnlTarjetas = new javax.swing.JPanel();
        pnlNuevaPeticion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlPendienteResultados = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlPendienteValidacion = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlGenerarInforme = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAcciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAcciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAcciones.setText("Acciones rápidas");
        lblAcciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 20, 1));
        add(lblAcciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        pnlTarjetas.setBackground(new java.awt.Color(255, 255, 255));
        pnlTarjetas.setMaximumSize(new java.awt.Dimension(1000, 600));
        pnlTarjetas.setLayout(new java.awt.GridBagLayout());

        pnlNuevaPeticion.setBackground(new java.awt.Color(243, 245, 249));
        pnlNuevaPeticion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlNuevaPeticion.setMaximumSize(new java.awt.Dimension(350, 100));
        pnlNuevaPeticion.setMinimumSize(new java.awt.Dimension(350, 100));
        pnlNuevaPeticion.setName(""); // NOI18N
        pnlNuevaPeticion.setPreferredSize(new java.awt.Dimension(350, 100));
        pnlNuevaPeticion.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nueva_peticion.png"))); // NOI18N
        jLabel2.setText("Nueva Petición");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        jLabel2.setMaximumSize(new java.awt.Dimension(400, 120));
        jLabel2.setMinimumSize(new java.awt.Dimension(400, 120));
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(400, 120));
        jLabel2.setRequestFocusEnabled(false);
        pnlNuevaPeticion.add(jLabel2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlTarjetas.add(pnlNuevaPeticion, gridBagConstraints);

        pnlPendienteResultados.setBackground(new java.awt.Color(243, 245, 249));
        pnlPendienteResultados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlPendienteResultados.setMaximumSize(new java.awt.Dimension(350, 100));
        pnlPendienteResultados.setMinimumSize(new java.awt.Dimension(350, 100));
        pnlPendienteResultados.setName(""); // NOI18N
        pnlPendienteResultados.setPreferredSize(new java.awt.Dimension(350, 100));
        pnlPendienteResultados.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pendiente_resultados.png"))); // NOI18N
        jLabel3.setText("<html>Pendientes de<br>resultados</html>");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        jLabel3.setMaximumSize(new java.awt.Dimension(400, 120));
        jLabel3.setMinimumSize(new java.awt.Dimension(400, 120));
        jLabel3.setPreferredSize(new java.awt.Dimension(400, 120));
        jLabel3.setRequestFocusEnabled(false);
        pnlPendienteResultados.add(jLabel3, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlTarjetas.add(pnlPendienteResultados, gridBagConstraints);

        pnlPendienteValidacion.setBackground(new java.awt.Color(243, 245, 249));
        pnlPendienteValidacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlPendienteValidacion.setMaximumSize(new java.awt.Dimension(350, 100));
        pnlPendienteValidacion.setMinimumSize(new java.awt.Dimension(350, 100));
        pnlPendienteValidacion.setName(""); // NOI18N
        pnlPendienteValidacion.setPreferredSize(new java.awt.Dimension(350, 100));
        pnlPendienteValidacion.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pendiente_validacion.png"))); // NOI18N
        jLabel4.setText("<html>Pendientes de<br>validación</html>");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        jLabel4.setMaximumSize(new java.awt.Dimension(400, 120));
        jLabel4.setMinimumSize(new java.awt.Dimension(400, 120));
        jLabel4.setPreferredSize(new java.awt.Dimension(400, 120));
        jLabel4.setRequestFocusEnabled(false);
        pnlPendienteValidacion.add(jLabel4, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlTarjetas.add(pnlPendienteValidacion, gridBagConstraints);

        pnlGenerarInforme.setBackground(new java.awt.Color(243, 245, 249));
        pnlGenerarInforme.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlGenerarInforme.setMaximumSize(new java.awt.Dimension(350, 100));
        pnlGenerarInforme.setMinimumSize(new java.awt.Dimension(350, 100));
        pnlGenerarInforme.setName(""); // NOI18N
        pnlGenerarInforme.setPreferredSize(new java.awt.Dimension(350, 100));
        pnlGenerarInforme.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/generar_informe.png"))); // NOI18N
        jLabel5.setText("Generar informe");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        jLabel5.setMaximumSize(new java.awt.Dimension(400, 120));
        jLabel5.setMinimumSize(new java.awt.Dimension(400, 120));
        jLabel5.setPreferredSize(new java.awt.Dimension(400, 120));
        jLabel5.setRequestFocusEnabled(false);
        pnlGenerarInforme.add(jLabel5, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlTarjetas.add(pnlGenerarInforme, gridBagConstraints);

        add(pnlTarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 118, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAcciones;
    private javax.swing.JPanel pnlGenerarInforme;
    private javax.swing.JPanel pnlNuevaPeticion;
    private javax.swing.JPanel pnlPendienteResultados;
    private javax.swing.JPanel pnlPendienteValidacion;
    private javax.swing.JPanel pnlTarjetas;
    // End of variables declaration//GEN-END:variables
}
