/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.awt.Cursor;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.border.Border;

/**
 *
 * @author leia6
 */
public final class PantallaPrincipal extends javax.swing.JFrame {

    private CardLayout cardLayout;

    public PantallaPrincipal() {
        initComponents();
        setSize(1300, 1000);
        setLocationRelativeTo(null);

        cardLayout = new CardLayout();
        panelPrincipal.setLayout(cardLayout);

        PanelInicio menuInicio = new PanelInicio(panelPrincipal);
        PanelNuevaPeticion pnlNuevaPeticion = new PanelNuevaPeticion(panelPrincipal);

        panelPrincipal.add(menuInicio, "Pantalla Inicio");
        panelPrincipal.add(pnlNuevaPeticion, "Nueva Peticion");

        aplicarHover(btnNuevaPeticion);
        aplicarHover(btnBuscarPeticion);
        aplicarHover(btnPendienteResultados);
        aplicarHover(btnPendienteValidacion);
        aplicarHover(btnBuscarPaciente);
        aplicarHover(btnRegistrarPaciente);
        aplicarHover(btnHistoricoPaciente);
        aplicarHover(btnInformePeticion);
        aplicarHover(btnEstadisticas);
    }

    private void aplicarHover(JButton boton) {
        Border bordeOriginal = boton.getBorder();

        Border normal = BorderFactory.createCompoundBorder(
                bordeOriginal,
                BorderFactory.createEmptyBorder(6, 10, 6, 10)
        );

        Border hover = BorderFactory.createCompoundBorder(
                bordeOriginal,
                BorderFactory.createEmptyBorder(6, 14, 6, 6)
        );

        boton.setBorder(normal);
        boton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        boton.setFocusPainted(false);

        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton.setBorder(hover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton.setBorder(normal);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        barraSuperior = new javax.swing.JPanel();
        lblLabTrack = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        menuLateral = new javax.swing.JPanel();
        menuPeticiones = new javax.swing.JPanel();
        lblPeticiones = new javax.swing.JLabel();
        btnBuscarPeticion = new javax.swing.JButton();
        btnNuevaPeticion = new javax.swing.JButton();
        btnPendienteResultados = new javax.swing.JButton();
        btnPendienteValidacion = new javax.swing.JButton();
        menuPacientes = new javax.swing.JPanel();
        lblPacientes = new javax.swing.JLabel();
        btnRegistrarPaciente = new javax.swing.JButton();
        btnBuscarPaciente = new javax.swing.JButton();
        btnHistoricoPaciente = new javax.swing.JButton();
        menuInformes = new javax.swing.JPanel();
        lblInformes = new javax.swing.JLabel();
        btnEstadisticas = new javax.swing.JButton();
        btnInformePeticion = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setLayout(new java.awt.BorderLayout());

        barraSuperior.setBackground(new java.awt.Color(75, 113, 167));
        barraSuperior.setMaximumSize(new java.awt.Dimension(32767, 90));
        barraSuperior.setMinimumSize(new java.awt.Dimension(100, 90));
        barraSuperior.setPreferredSize(new java.awt.Dimension(1382, 90));
        barraSuperior.setLayout(new java.awt.BorderLayout());

        lblLabTrack.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblLabTrack.setForeground(new java.awt.Color(255, 255, 255));
        lblLabTrack.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLabTrack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLabTrack.png"))); // NOI18N
        lblLabTrack.setText("LabTrack");
        lblLabTrack.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblLabTrack.setMaximumSize(new java.awt.Dimension(100, 72));
        lblLabTrack.setMinimumSize(new java.awt.Dimension(100, 72));
        lblLabTrack.setPreferredSize(new java.awt.Dimension(100, 72));
        barraSuperior.add(lblLabTrack, java.awt.BorderLayout.CENTER);

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario");
        lblUsuario.setPreferredSize(new java.awt.Dimension(300, 14));
        barraSuperior.add(lblUsuario, java.awt.BorderLayout.LINE_END);

        fondo.add(barraSuperior, java.awt.BorderLayout.PAGE_START);

        menuLateral.setBackground(new java.awt.Color(243, 245, 249));
        menuLateral.setMaximumSize(new java.awt.Dimension(2147483647, 560));
        menuLateral.setPreferredSize(new java.awt.Dimension(220, 640));
        menuLateral.setLayout(new javax.swing.BoxLayout(menuLateral, javax.swing.BoxLayout.Y_AXIS));

        menuPeticiones.setBackground(new java.awt.Color(243, 245, 249));
        menuPeticiones.setMaximumSize(new java.awt.Dimension(2147483647, 280));
        menuPeticiones.setMinimumSize(new java.awt.Dimension(200, 280));
        menuPeticiones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPeticiones.setBackground(new java.awt.Color(215, 232, 247));
        lblPeticiones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPeticiones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPeticiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carpeta.png"))); // NOI18N
        lblPeticiones.setText("PETICIONES");
        lblPeticiones.setOpaque(true);
        menuPeticiones.add(lblPeticiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 27, 220, 50));

        btnBuscarPeticion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnBuscarPeticion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        btnBuscarPeticion.setText("Buscar petición");
        btnBuscarPeticion.setBorderPainted(false);
        btnBuscarPeticion.setContentAreaFilled(false);
        btnBuscarPeticion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuPeticiones.add(btnBuscarPeticion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, 40));

        btnNuevaPeticion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnNuevaPeticion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus.png"))); // NOI18N
        btnNuevaPeticion.setText("<html>Registrar nueva<br>petición</html>");
        btnNuevaPeticion.setBorderPainted(false);
        btnNuevaPeticion.setContentAreaFilled(false);
        btnNuevaPeticion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNuevaPeticion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaPeticionActionPerformed(evt);
            }
        });
        menuPeticiones.add(btnNuevaPeticion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 40));

        btnPendienteResultados.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnPendienteResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/resultados.png"))); // NOI18N
        btnPendienteResultados.setText("<html>Pendientes de<br>resultados</html>");
        btnPendienteResultados.setBorderPainted(false);
        btnPendienteResultados.setContentAreaFilled(false);
        btnPendienteResultados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPendienteResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendienteResultadosActionPerformed(evt);
            }
        });
        menuPeticiones.add(btnPendienteResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, 40));

        btnPendienteValidacion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnPendienteValidacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/validacion.png"))); // NOI18N
        btnPendienteValidacion.setText("<html>Pendientes de<br>validación</html>");
        btnPendienteValidacion.setBorderPainted(false);
        btnPendienteValidacion.setContentAreaFilled(false);
        btnPendienteValidacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPendienteValidacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendienteValidacionActionPerformed(evt);
            }
        });
        menuPeticiones.add(btnPendienteValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 220, 40));

        menuLateral.add(menuPeticiones);

        menuPacientes.setBackground(new java.awt.Color(243, 245, 249));
        menuPacientes.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        menuPacientes.setMinimumSize(new java.awt.Dimension(200, 200));
        menuPacientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPacientes.setBackground(new java.awt.Color(215, 232, 247));
        lblPacientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        lblPacientes.setText("PACIENTES");
        lblPacientes.setMaximumSize(new java.awt.Dimension(96, 32));
        lblPacientes.setMinimumSize(new java.awt.Dimension(96, 32));
        lblPacientes.setOpaque(true);
        menuPacientes.add(lblPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 40));

        btnRegistrarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnRegistrarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo_usuario.png"))); // NOI18N
        btnRegistrarPaciente.setText("Registrar paciente");
        btnRegistrarPaciente.setBorderPainted(false);
        btnRegistrarPaciente.setContentAreaFilled(false);
        btnRegistrarPaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPacienteActionPerformed(evt);
            }
        });
        menuPacientes.add(btnRegistrarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 40));

        btnBuscarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnBuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        btnBuscarPaciente.setText("Buscar paciente");
        btnBuscarPaciente.setBorderPainted(false);
        btnBuscarPaciente.setContentAreaFilled(false);
        btnBuscarPaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteActionPerformed(evt);
            }
        });
        menuPacientes.add(btnBuscarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 40));

        btnHistoricoPaciente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnHistoricoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historico.png"))); // NOI18N
        btnHistoricoPaciente.setText("Histórico paciente");
        btnHistoricoPaciente.setBorderPainted(false);
        btnHistoricoPaciente.setContentAreaFilled(false);
        btnHistoricoPaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHistoricoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoPacienteActionPerformed(evt);
            }
        });
        menuPacientes.add(btnHistoricoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 40));

        menuLateral.add(menuPacientes);

        menuInformes.setBackground(new java.awt.Color(243, 245, 249));
        menuInformes.setMaximumSize(new java.awt.Dimension(2147483647, 160));
        menuInformes.setMinimumSize(new java.awt.Dimension(220, 160));
        menuInformes.setName(""); // NOI18N
        menuInformes.setOpaque(false);
        menuInformes.setPreferredSize(new java.awt.Dimension(220, 150));
        menuInformes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInformes.setBackground(new java.awt.Color(215, 232, 247));
        lblInformes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInformes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barchart.png"))); // NOI18N
        lblInformes.setText("INFORMES");
        lblInformes.setMaximumSize(new java.awt.Dimension(92, 32));
        lblInformes.setMinimumSize(new java.awt.Dimension(92, 32));
        lblInformes.setOpaque(true);
        menuInformes.add(lblInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 37));

        btnEstadisticas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estadistica.png"))); // NOI18N
        btnEstadisticas.setText("Estadísticas");
        btnEstadisticas.setBorderPainted(false);
        btnEstadisticas.setContentAreaFilled(false);
        btnEstadisticas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuInformes.add(btnEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 220, 40));

        btnInformePeticion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnInformePeticion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informes.png"))); // NOI18N
        btnInformePeticion.setText("Informe por petición");
        btnInformePeticion.setBorderPainted(false);
        btnInformePeticion.setContentAreaFilled(false);
        btnInformePeticion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInformePeticion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformePeticionActionPerformed(evt);
            }
        });
        menuInformes.add(btnInformePeticion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 40));

        menuLateral.add(menuInformes);

        fondo.add(menuLateral, java.awt.BorderLayout.LINE_START);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new java.awt.CardLayout());
        fondo.add(panelPrincipal, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPendienteValidacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendienteValidacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPendienteValidacionActionPerformed

    private void btnNuevaPeticionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaPeticionActionPerformed
        cardLayout.show(panelPrincipal, "Nueva Peticion");
    }//GEN-LAST:event_btnNuevaPeticionActionPerformed

    private void btnPendienteResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendienteResultadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPendienteResultadosActionPerformed

    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPacienteActionPerformed

    private void btnHistoricoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistoricoPacienteActionPerformed

    private void btnInformePeticionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformePeticionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInformePeticionActionPerformed

    private void btnRegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    /*    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JButton btnBuscarPaciente;
    private javax.swing.JButton btnBuscarPeticion;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnHistoricoPaciente;
    private javax.swing.JButton btnInformePeticion;
    private javax.swing.JButton btnNuevaPeticion;
    private javax.swing.JButton btnPendienteResultados;
    private javax.swing.JButton btnPendienteValidacion;
    private javax.swing.JButton btnRegistrarPaciente;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel lblInformes;
    private javax.swing.JLabel lblLabTrack;
    private javax.swing.JLabel lblPacientes;
    private javax.swing.JLabel lblPeticiones;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel menuInformes;
    private javax.swing.JPanel menuLateral;
    private javax.swing.JPanel menuPacientes;
    private javax.swing.JPanel menuPeticiones;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
