/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import app.Sesion;
import java.awt.CardLayout;
import java.awt.Cursor;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author leia6
 */
public final class PantallaPrincipal extends javax.swing.JFrame {

    private CardLayout cardLayout;
    PanelNuevaPeticion pnlNuevaPeticion;
    PanelBuscarPeticion pnlBuscarPeticion;
    PanelPendientesResultados pnlPendResultados;
    PanelPendientesValidacion pnlPendValidacion;
    PanelInformesPeticion pnlInformesPeticion;
    PanelBuscarPaciente pnlBuscarPaciente;

    public PantallaPrincipal() {
        initComponents();
        setSize(1650, 1200);
        setLocationRelativeTo(null);
        aplicarPermisos();
        setTitle("LabTrack");

        cardLayout = new CardLayout();
        panelPrincipal.setLayout(cardLayout);

        pnlNuevaPeticion = new PanelNuevaPeticion(panelPrincipal);
        PanelGestionPeticion pnlGestionPeticion = new PanelGestionPeticion(panelPrincipal);
        pnlBuscarPeticion = new PanelBuscarPeticion(panelPrincipal, pnlGestionPeticion);
        pnlBuscarPaciente = new PanelBuscarPaciente(panelPrincipal);
        PanelHistoricoPaciente pnlHistoricoPaciente = new PanelHistoricoPaciente(panelPrincipal, pnlGestionPeticion);
        pnlPendResultados = new PanelPendientesResultados(panelPrincipal, pnlGestionPeticion);
        pnlPendValidacion = new PanelPendientesValidacion(panelPrincipal, pnlGestionPeticion);
        pnlInformesPeticion = new PanelInformesPeticion(panelPrincipal);
        PanelEstadisticas pnlEstadisticas = new PanelEstadisticas(panelPrincipal);
        PanelInicio menuInicio = new PanelInicio(panelPrincipal, pnlPendResultados, pnlPendValidacion, pnlInformesPeticion);

        panelPrincipal.add(menuInicio, "Pantalla Inicio");
        panelPrincipal.add(pnlNuevaPeticion, "Nueva Peticion");
        panelPrincipal.add(pnlBuscarPeticion, "Buscar Peticion");
        panelPrincipal.add(pnlBuscarPaciente, "Buscar Paciente");
        panelPrincipal.add(pnlHistoricoPaciente, "Historico paciente");
        panelPrincipal.add(pnlGestionPeticion, "Gestion peticion");
        panelPrincipal.add(pnlPendResultados, "Pendiente Resultados");
        panelPrincipal.add(pnlPendValidacion, "Pendiente Validacion");
        panelPrincipal.add(pnlInformesPeticion, "Informes");
        panelPrincipal.add(pnlEstadisticas, "Estadisticas");

        aplicarHover(btnNuevaPeticion);
        aplicarHover(btnBuscarPeticion);
        aplicarHover(btnPendienteResultados);
        aplicarHover(btnPendienteValidacion);
        aplicarHover(btnBuscarPaciente);
        aplicarHover(btnRegistrarPaciente);
        aplicarHover(btnHistoricoPaciente);
        aplicarHover(btnInformePeticion);
        aplicarHover(btnEstadisticas);
    }

    private void aplicarPermisos() {
        if (Sesion.esTecnico()) {
            btnPendienteValidacion.setEnabled(false);
            btnInformePeticion.setEnabled(false);
            btnEstadisticas.setEnabled(false);
        }

        if (Sesion.esFacultativo()) {
            btnNuevaPeticion.setEnabled(false);
            btnPendienteResultados.setEnabled(false);
            btnRegistrarPaciente.setEnabled(false);
            btnBuscarPeticion.setEnabled(false);
        }

        lblUsuario.setText(Sesion.getUsername() + " - " + Sesion.getRol());
    }

    private void aplicarHover(JButton boton) {
        Border bordeOriginal = boton.getBorder();

        Border normal = BorderFactory.createCompoundBorder(
                bordeOriginal,
                BorderFactory.createEmptyBorder(6, 10, 6, 10)
        );

        Border hover = BorderFactory.createCompoundBorder(
                bordeOriginal,
                BorderFactory.createEmptyBorder(6, 14, 6, 6)
        );

        boton.setBorder(normal);
        boton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        boton.setFocusPainted(false);

        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton.setBorder(hover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton.setBorder(normal);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        barraSuperior = new javax.swing.JPanel();
        lblLabTrack = new javax.swing.JLabel();
        pnlUsuario = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        pnlBtnLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlCentro = new javax.swing.JPanel();
        menuLateral = new javax.swing.JPanel();
        menuPeticiones = new javax.swing.JPanel();
        lblPeticiones = new javax.swing.JLabel();
        btnBuscarPeticion = new javax.swing.JButton();
        btnNuevaPeticion = new javax.swing.JButton();
        btnPendienteResultados = new javax.swing.JButton();
        btnPendienteValidacion = new javax.swing.JButton();
        menuPacientes = new javax.swing.JPanel();
        lblPacientes = new javax.swing.JLabel();
        btnRegistrarPaciente = new javax.swing.JButton();
        btnBuscarPaciente = new javax.swing.JButton();
        btnHistoricoPaciente = new javax.swing.JButton();
        menuInformes = new javax.swing.JPanel();
        lblInformes = new javax.swing.JLabel();
        btnEstadisticas = new javax.swing.JButton();
        btnInformePeticion = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setLayout(new java.awt.BorderLayout());

        barraSuperior.setBackground(new java.awt.Color(75, 113, 167));
        barraSuperior.setMaximumSize(new java.awt.Dimension(32767, 90));
        barraSuperior.setMinimumSize(new java.awt.Dimension(100, 90));
        barraSuperior.setPreferredSize(new java.awt.Dimension(1382, 90));
        barraSuperior.setLayout(new java.awt.BorderLayout());

        lblLabTrack.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblLabTrack.setForeground(new java.awt.Color(255, 255, 255));
        lblLabTrack.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLabTrack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLabTrack.png"))); // NOI18N
        lblLabTrack.setText("LabTrack");
        lblLabTrack.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblLabTrack.setMaximumSize(new java.awt.Dimension(100, 72));
        lblLabTrack.setMinimumSize(new java.awt.Dimension(100, 72));
        lblLabTrack.setPreferredSize(new java.awt.Dimension(100, 72));
        barraSuperior.add(lblLabTrack, java.awt.BorderLayout.CENTER);

        pnlUsuario.setBackground(new java.awt.Color(75, 113, 167));
        pnlUsuario.setMinimumSize(new java.awt.Dimension(500, 100));
        pnlUsuario.setPreferredSize(new java.awt.Dimension(500, 90));
        pnlUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario.setText("Usuario");
        pnlUsuario.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, 30, 820, -1));

        pnlBtnLogout.setBackground(new java.awt.Color(75, 113, 167));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logout.png"))); // NOI18N
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogoutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnLogoutLayout = new javax.swing.GroupLayout(pnlBtnLogout);
        pnlBtnLogout.setLayout(pnlBtnLogoutLayout);
        pnlBtnLogoutLayout.setHorizontalGroup(
            pnlBtnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBtnLogoutLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(24, 24, 24))
        );
        pnlBtnLogoutLayout.setVerticalGroup(
            pnlBtnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBtnLogoutLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(28, 28, 28))
        );

        pnlUsuario.add(pnlBtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, 90));

        barraSuperior.add(pnlUsuario, java.awt.BorderLayout.LINE_END);

        fondo.add(barraSuperior, java.awt.BorderLayout.NORTH);

        pnlCentro.setMinimumSize(new java.awt.Dimension(220, 850));
        pnlCentro.setPreferredSize(new java.awt.Dimension(220, 850));
        pnlCentro.setLayout(new java.awt.BorderLayout());

        menuLateral.setBackground(new java.awt.Color(243, 245, 249));
        menuLateral.setMaximumSize(new java.awt.Dimension(2147483647, 640));
        menuLateral.setPreferredSize(new java.awt.Dimension(220, 640));
        menuLateral.setLayout(new javax.swing.BoxLayout(menuLateral, javax.swing.BoxLayout.Y_AXIS));

        menuPeticiones.setBackground(new java.awt.Color(243, 245, 249));
        menuPeticiones.setMaximumSize(new java.awt.Dimension(2147483647, 280));
        menuPeticiones.setMinimumSize(new java.awt.Dimension(200, 280));
        menuPeticiones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPeticiones.setBackground(new java.awt.Color(215, 232, 247));
        lblPeticiones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPeticiones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPeticiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carpeta.png"))); // NOI18N
        lblPeticiones.setText("PETICIONES");
        lblPeticiones.setOpaque(true);
        menuPeticiones.add(lblPeticiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 27, 220, 50));

        btnBuscarPeticion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnBuscarPeticion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        btnBuscarPeticion.setText("Buscar petición");
        btnBuscarPeticion.setBorderPainted(false);
        btnBuscarPeticion.setContentAreaFilled(false);
        btnBuscarPeticion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuscarPeticion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPeticionActionPerformed(evt);
            }
        });
        menuPeticiones.add(btnBuscarPeticion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, 40));

        btnNuevaPeticion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnNuevaPeticion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus.png"))); // NOI18N
        btnNuevaPeticion.setText("<html>Registrar nueva<br>petición</html>");
        btnNuevaPeticion.setBorderPainted(false);
        btnNuevaPeticion.setContentAreaFilled(false);
        btnNuevaPeticion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNuevaPeticion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaPeticionActionPerformed(evt);
            }
        });
        menuPeticiones.add(btnNuevaPeticion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 40));

        btnPendienteResultados.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnPendienteResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/resultados.png"))); // NOI18N
        btnPendienteResultados.setText("<html>Pendientes de<br>resultados</html>");
        btnPendienteResultados.setBorderPainted(false);
        btnPendienteResultados.setContentAreaFilled(false);
        btnPendienteResultados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPendienteResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendienteResultadosActionPerformed(evt);
            }
        });
        menuPeticiones.add(btnPendienteResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, 40));

        btnPendienteValidacion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnPendienteValidacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/validacion.png"))); // NOI18N
        btnPendienteValidacion.setText("<html>Pendientes de<br>validación</html>");
        btnPendienteValidacion.setBorderPainted(false);
        btnPendienteValidacion.setContentAreaFilled(false);
        btnPendienteValidacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPendienteValidacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendienteValidacionActionPerformed(evt);
            }
        });
        menuPeticiones.add(btnPendienteValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 220, 40));

        menuLateral.add(menuPeticiones);

        menuPacientes.setBackground(new java.awt.Color(243, 245, 249));
        menuPacientes.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        menuPacientes.setMinimumSize(new java.awt.Dimension(200, 200));
        menuPacientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPacientes.setBackground(new java.awt.Color(215, 232, 247));
        lblPacientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        lblPacientes.setText("PACIENTES");
        lblPacientes.setMaximumSize(new java.awt.Dimension(96, 32));
        lblPacientes.setMinimumSize(new java.awt.Dimension(96, 32));
        lblPacientes.setOpaque(true);
        menuPacientes.add(lblPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 40));

        btnRegistrarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnRegistrarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo_usuario.png"))); // NOI18N
        btnRegistrarPaciente.setText("Registrar paciente");
        btnRegistrarPaciente.setBorderPainted(false);
        btnRegistrarPaciente.setContentAreaFilled(false);
        btnRegistrarPaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPacienteActionPerformed(evt);
            }
        });
        menuPacientes.add(btnRegistrarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 40));

        btnBuscarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnBuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        btnBuscarPaciente.setText("Buscar paciente");
        btnBuscarPaciente.setBorderPainted(false);
        btnBuscarPaciente.setContentAreaFilled(false);
        btnBuscarPaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteActionPerformed(evt);
            }
        });
        menuPacientes.add(btnBuscarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 40));

        btnHistoricoPaciente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnHistoricoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historico.png"))); // NOI18N
        btnHistoricoPaciente.setText("Histórico paciente");
        btnHistoricoPaciente.setBorderPainted(false);
        btnHistoricoPaciente.setContentAreaFilled(false);
        btnHistoricoPaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHistoricoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoPacienteActionPerformed(evt);
            }
        });
        menuPacientes.add(btnHistoricoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 40));

        menuLateral.add(menuPacientes);

        menuInformes.setBackground(new java.awt.Color(243, 245, 249));
        menuInformes.setMaximumSize(new java.awt.Dimension(2147483647, 160));
        menuInformes.setMinimumSize(new java.awt.Dimension(220, 160));
        menuInformes.setName(""); // NOI18N
        menuInformes.setOpaque(false);
        menuInformes.setPreferredSize(new java.awt.Dimension(220, 150));
        menuInformes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInformes.setBackground(new java.awt.Color(215, 232, 247));
        lblInformes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInformes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barchart.png"))); // NOI18N
        lblInformes.setText("INFORMES");
        lblInformes.setMaximumSize(new java.awt.Dimension(92, 32));
        lblInformes.setMinimumSize(new java.awt.Dimension(92, 32));
        lblInformes.setOpaque(true);
        menuInformes.add(lblInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 37));

        btnEstadisticas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estadistica.png"))); // NOI18N
        btnEstadisticas.setText("Estadísticas");
        btnEstadisticas.setBorderPainted(false);
        btnEstadisticas.setContentAreaFilled(false);
        btnEstadisticas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });
        menuInformes.add(btnEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 220, 40));

        btnInformePeticion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnInformePeticion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informes.png"))); // NOI18N
        btnInformePeticion.setText("<html>Informes por <br>petición</html>");
        btnInformePeticion.setBorderPainted(false);
        btnInformePeticion.setContentAreaFilled(false);
        btnInformePeticion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInformePeticion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformePeticionActionPerformed(evt);
            }
        });
        menuInformes.add(btnInformePeticion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 40));

        menuLateral.add(menuInformes);

        pnlCentro.add(menuLateral, java.awt.BorderLayout.WEST);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setMaximumSize(new java.awt.Dimension(2147483647, 700));
        panelPrincipal.setMinimumSize(new java.awt.Dimension(0, 700));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(0, 700));
        panelPrincipal.setLayout(new java.awt.CardLayout());
        pnlCentro.add(panelPrincipal, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(pnlCentro);

        fondo.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPendienteValidacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendienteValidacionActionPerformed
        pnlBuscarPaciente.limpiarFormulario();

        if (!pnlNuevaPeticion.confirmarSalida()) {
            return;
        }
        if (!pnlBuscarPeticion.confirmarSalida()) {
            return;
        }

        pnlNuevaPeticion.limpiarFormulario();
        pnlBuscarPeticion.limpiarFormulario();

        pnlPendValidacion.cargarPendientes();
        cardLayout.show(panelPrincipal, "Pendiente Validacion");
    }//GEN-LAST:event_btnPendienteValidacionActionPerformed

    private void btnNuevaPeticionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaPeticionActionPerformed
        pnlBuscarPaciente.limpiarFormulario();

        if (!pnlBuscarPeticion.confirmarSalida()) {
            return;
        }

        pnlBuscarPeticion.limpiarFormulario();

        cardLayout.show(panelPrincipal, "Nueva Peticion");
    }//GEN-LAST:event_btnNuevaPeticionActionPerformed

    private void btnPendienteResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendienteResultadosActionPerformed
        pnlBuscarPaciente.limpiarFormulario();

        if (!pnlNuevaPeticion.confirmarSalida()) {
            return;
        }
        if (!pnlBuscarPeticion.confirmarSalida()) {
            return;
        }

        pnlNuevaPeticion.limpiarFormulario();
        pnlBuscarPeticion.limpiarFormulario();

        pnlPendResultados.cargarPendientes();
        cardLayout.show(panelPrincipal, "Pendiente Resultados");
    }//GEN-LAST:event_btnPendienteResultadosActionPerformed

    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed
        if (!pnlNuevaPeticion.confirmarSalida()) {
            return;
        }
        if (!pnlBuscarPeticion.confirmarSalida()) {
            return;
        }

        pnlNuevaPeticion.limpiarFormulario();
        pnlBuscarPeticion.limpiarFormulario();

        cardLayout.show(panelPrincipal, "Buscar Paciente");
    }//GEN-LAST:event_btnBuscarPacienteActionPerformed

    private void btnHistoricoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoPacienteActionPerformed
        pnlBuscarPaciente.limpiarFormulario();

        if (!pnlNuevaPeticion.confirmarSalida()) {
            return;
        }
        if (!pnlBuscarPeticion.confirmarSalida()) {
            return;
        }

        pnlNuevaPeticion.limpiarFormulario();
        pnlBuscarPeticion.limpiarFormulario();

        cardLayout.show(panelPrincipal, "Historico paciente");
    }//GEN-LAST:event_btnHistoricoPacienteActionPerformed

    private void btnInformePeticionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformePeticionActionPerformed
        pnlBuscarPaciente.limpiarFormulario();

        if (!pnlNuevaPeticion.confirmarSalida()) {
            return;
        }
        if (!pnlBuscarPeticion.confirmarSalida()) {
            return;
        }

        pnlNuevaPeticion.limpiarFormulario();
        pnlBuscarPeticion.limpiarFormulario();

        pnlInformesPeticion.limpiarFormulario();
        pnlInformesPeticion.cargarPendientesInformar();
        cardLayout.show(panelPrincipal, "Informes");
    }//GEN-LAST:event_btnInformePeticionActionPerformed

    private void btnRegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPacienteActionPerformed
        pnlBuscarPaciente.limpiarFormulario();

        if (!pnlNuevaPeticion.confirmarSalida()) {
            return;
        }
        if (!pnlBuscarPeticion.confirmarSalida()) {
            return;
        }

        pnlNuevaPeticion.limpiarFormulario();
        pnlBuscarPeticion.limpiarFormulario();

        DialogoAltaPaciente dialog = new DialogoAltaPaciente(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnRegistrarPacienteActionPerformed

    private void btnBuscarPeticionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPeticionActionPerformed
        pnlBuscarPaciente.limpiarFormulario();

        if (!pnlNuevaPeticion.confirmarSalida()) {
            return;
        }

        pnlNuevaPeticion.limpiarFormulario();

        cardLayout.show(panelPrincipal, "Buscar Peticion");
    }//GEN-LAST:event_btnBuscarPeticionActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        pnlBuscarPaciente.limpiarFormulario();

        cardLayout.show(panelPrincipal, "Estadisticas");
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMousePressed
        if (!pnlNuevaPeticion.confirmarSalida()) {
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que deseas cerrar sesión?",
                "Cerrar sesión",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        Sesion.cerrarSesion();

        VentanaLogin login = new VentanaLogin();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnLogoutMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JButton btnBuscarPaciente;
    private javax.swing.JButton btnBuscarPeticion;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnHistoricoPaciente;
    private javax.swing.JButton btnInformePeticion;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JButton btnNuevaPeticion;
    private javax.swing.JButton btnPendienteResultados;
    private javax.swing.JButton btnPendienteValidacion;
    private javax.swing.JButton btnRegistrarPaciente;
    private javax.swing.JPanel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInformes;
    private javax.swing.JLabel lblLabTrack;
    private javax.swing.JLabel lblPacientes;
    private javax.swing.JLabel lblPeticiones;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel menuInformes;
    private javax.swing.JPanel menuLateral;
    private javax.swing.JPanel menuPacientes;
    private javax.swing.JPanel menuPeticiones;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel pnlBtnLogout;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlUsuario;
    // End of variables declaration//GEN-END:variables
}
